### PR TITLE
Issue 41 - Add choice description to email

### PR DESCRIPTION
**Pull request by andrewhancox**
Added choice description to the allocation notification message as per issue 41.

### CODE REVIEW

**Comment by Kathrin84** [comment]
Hi Tobias,
I've tested the patch and as long as the student's preferred language is English it works (due to lang/en).
Cheers,
Kathrin

**Comment by TechnikLearnweb** [comment]
Can one of the admins verify this patch?

**Comment by tobiasreischmann** [comment]
test this please

**Comment by tobiasreischmann** [comment]
Thanks for your work

**Comment by tobiasreischmann** [comment]
Fixes #41

**Pull request merged**
