### PR TITLE
Improvements for Ratingstable and Manual Allocation Form

### PR DESCRIPTION
**Pull request by tobiasreischmann**
Following changes were made:

- Embedded the ratings and allocation table into the manual allocation form.
- Added paging functionality to both tables
- Added sort functionality to both tables
- Added initial filters to both tables
- Created a new and more intuitive filter for the manual allocation form
- In the manual allocation form allocations can now be unselected and therefore deleted

### CODE REVIEW

**Comment by tobiasreischmann** [comment]
Fixes #73,  #72
Also offers some functionality to #11

**Comment by Kathrin84** [comment]
Hi Tobi,
Alex asked me to test your patch and give you some feedback. First of all: Wow, you did a lot of work with this! Thanks for that!

Noow, here are my comments:

* Design
** The table looks quite fancy with the icons, that's really nice! 👍 
** Unfortunately, if the viewport is too small so that the table adds horizontal scroll bars, the check icon of the allocated options move with the scroll bar and leave their checkbox. Here's a short screencast that shows this effect:
[manual_allocation_checkicon.mp4.zip](https://github.com/learnweb/moodle-mod_ratingallocate/files/919318/manual_allocation_checkicon.mp4.zip)

* Pagination
This feature works fine. Nevertheless, I believe at least Alex would miss a possibility to display all entries on one page again as an option. But I'm not quite sure about this, maybe he gives a seperate feedback on this aspect.

* Table filtering
I'm not quite sure, how these two filters should work, but I tell you what I would expect and what's the result that's being presented to me:
** Show users with no rating: I'm a bit confused about the fact that this filter also shows users with existing ratings:
manual_alloctaion_filter_norating
** Show only users with no allocation: If this option is checked _solely_, no users will be shown even if there are some that definitely don't have an allocation yet.
** If both filters are enabled, users will be displayed that have no rating and no allocation. I think this is as expected.

* Allocation
The possibility to set the manual allocation for a user ist fast and comfortable. However I stubled over the missing functionality to deselect a set manual allocation completely. At the moment a once set allocation can only be changed to another option but not, right?

That's all. I hope this is not too much or too frustrating for you.
Cheers, Kathrin

**Comment by Dagefoerde** [comment]
Hi Katrin, thanks for your screencast of the moving checkmarks issue. I was able to reproduce it. My latest commit should fix that issue.
screenshot

By the way, the screenshot shows that Tobias's boxes don't look that nice on Chrome/Linux. Sadly, they already looked that way before I started fixing... :(

Also, I felt obliged to add some explanatory comments to the CSS. Hope they will be useful someday.

Cheers

**Comment by abias** [comment]
Thanks, Kathrin, for the extensive feedback.

> Nevertheless, I believe at least Alex would miss a possibility to display all entries on one page again as an option. But I'm not quite sure about this, maybe he gives a seperate feedback on this aspect.

As I read my name here, I will add my two cents:
Yes, a "show all" option would be really appreciated. I always use this functionality with paginated lists which are only paginated to few (<5) page and / or don't have a possibility to set the amount of list entries on one page.
However, I am afraid that the Moodle table API might not have a "show all" feature for pagination, so if it is not easily to add this feature, let it be.

Thanks,
Alex

**Comment by tobiasreischmann** [comment]
Hi Kathrin,
thanks for your remarks. Since Jan already solved the first problem, I will tackle the other issues now.
* Pagination: Yes, I would like a possibility to show all entries as well. However, how Alex already identified, there is now functionality offered by the tablelib to do this. As a workaround I at least increased the number of entries per page to 20. The same amount as in the user overview of a course. I will think about adding a dropdown to the filterbar, which allows to choose from different page sizes.
* Table filtering: The filters work as intended. However, I have to admit that my intensions were not obvious. I just changed the meaning and the way the filters work. Can you have a look, if they are now more intuitive?
* Allocation: There was still a little bug. However, it is now possible to delete an allocation by just unselecting the respective box. This was not yet possible, if you submitted a form with no allocation at all (fixed now). 

Again thanks for your review.
Cheers Tobias

**Pull request merged**
