### PR TITLE
Show available spots

### LINKED ISSUE #14: Show Available Spots
During the rating process it might be interesting to see the maximum available spots for every choice in the listing. The maximum for available spots is an attribute that every choice already has, so it probably only has to be rendered.

This was requested quite often, however it is still advisable to make this optional if that is not a too big deal. To have it always displayed is also fine.

### PR DESCRIPTION
**Pull request by Dagefoerde**
Display max. number of members per choice to user.
In the course of writing this, I changed two files so that they adhere to the moodle code style guidelines.

This resolves #14 as discussed there. That is, currently the number of available spots is always displayed. If this should be optional, a further issue needs to be opened.

### CODE REVIEW

**Comment by tobiasreischmann** [comment]
I don't like the place and the string used to display the numer of available spots.
First seperate the language strings of the config and the displayed string.
Second possibly place the string below the description or behind an additional hint field?

**Comment by Dagefoerde** [comment]
Updated my suggestion. Furthermore, I am considering to add explanatory texts and to make the word "Student" adaptive to course role naming settings.
=> Please don't merge yet.

**Comment by Dagefoerde** [comment]
Sadly, there is  no way of getting the plural form of a role. Therefore, I would like to leave `Student` in the language string. The language strings may be changed by users anyway.
The display is slightly different from what we discussed, but might nevertheless be an interesting option.

**Comment by tobiasreischmann** [comment]
I just looked into some other modules and they all use the term 'student' somethere in the lang file. Thus you can use it this way, too.

**Pull request merged**
