### PR TITLE
Use HTML editor for choice explanations.

### PR DESCRIPTION
**Pull request by DrCuriosity**
Changes the choice explanation element from 'text' to 'editor'.

Text in existing choices will be rendered as normal; explanations will be updated to HTML format whenever the form is next edited.

Internal file management / upload is presently disabled, but external image and file URLs can be inserted via the editor, supporting embedding within the explanation markup.

### CODE REVIEW

**Comment by abias** [comment]
Hi @DrCuriosity ,

thank you for submitting this PR! This change makes sense in my point of view.

One important note from me:
Please have a look at issue #223 which I have just created.
If I understand it correctly (but without having tested it) your change to a rich text editor will not solve but also inherit this bug.

It would be awesome if you could have a look at the length of the `explanation` field and would solve this bug on-the-fly with your great improvement.

Cheers,
Alex

**Comment by danmarsden** [comment]
Thanks @abias - good catch, we should definitely swap that field out to being a text field rather than varchar - David can you please update this one with that change? - I think it makes sense to combine them into the same PR.

**Comment by DrCuriosity** [comment]
Hi @abias,
That size limit does look like a problem. Indeed, with markup included in the field, a user would hit the 255-character limit even more quickly.

I think it makes sense to change the `explanation` field to be a text type for added versatility, as @danmarsden suggests. I will add this improvement to my PR shortly. Thanks from bringing it to our attention!

**Comment by abias** [comment]
Thanks @DrCuriosity for handling the bug report so quickly and for solving the problem within this PR.

And in terms of credits:
The credits for finding this bug go to @h3ssto who reported this problem in a support case to us at Ulm university. I am just to one who reported it here :)

**Comment by DrCuriosity** [comment]
Sure, I don't have Behat set up on my dev environment just yet, but this is a good excuse to do so.

**Comment by DrCuriosity** [comment]
Hi @justusdieckmann,

It definitely looks like Behat can't find the text editor element in the form, so it's failing on:
```gherkin
    And I add a new choice with the values:
      | title       | My only choice |
      | explanation | Test           |
      | maxsize     |	1            |
```
We might be able to fix it with an override to the appropriate function in behat_mod_ratingallocate.php to encourage it to explicitly use a `behat_form_editor` for that field.

**Comment by danmarsden** [comment]
I'm pretty sure this is the fix for those behat issues:
https://github.com/danmarsden/moodle-mod_ratingallocate/commit/5035951c8a3bb63c3af22bd7e4deda3b76432b39

**Comment by justusdieckmann** [comment]
Yes it is, I was just looking at the same thing, using `id_explanation` instead of the label does also work, but using the label in the behattest is maybe more appropriate.

One thing that still needs to be done is that, now, that the description can contain arbitrary html, it needs to be passed through format_text everywhere it is displayed. (I believe this would only be in the choice overview table, and in the mforms for displaying the choices to students)

**Comment by danmarsden** [comment]
Good catch - thanks @justusdieckmann  - we'll get that change through shortly.

thanks!

**Review by justusdieckmann — APPROVED** [review]
Thank you @DrCuriosity @danmarsden!

**Pull request merged**
