### PR TITLE
Feature/add dates to course calendar

### LINKED ISSUE #209: Feature Request: Add rating start/end date to course calendar
It would be nice if the rating start/end dates would be added automatically to the course calendar similar to the feedback or the assignment activities.

### PR DESCRIPTION
**Pull request by irinahpe**
Creates course calendar events for the beginning and the end of the rating-phase. Only students who are able to rate can see the events.
closes #209

### CODE REVIEW

**Comment by PhMemmel** [comment]
The version bump to a version BEFORE the current master version is a bit unfortunate for everyone already running master. Would be nice if this could be fixed.

**Comment by Laur0r** [comment]
Hey @PhMemmel, to what version from which commit are you refering to? As far as I have seen, we have been on version 2023050900 on the master branch for three weeks.

**Comment by PhMemmel** [comment]
Hi @Laur0r, thank you for the fast response. Sorry for the noise, I doublechecked and it seems to be fine. I probably got confused by this commit: https://github.com/learnweb/moodle-mod_ratingallocate/commit/9a9ff923c26b5cf8ed5c4b364cfc28d1e9f1d840

But looks all good.

**Comment by Laur0r** [comment]
Great, thank you for checking and for keeping an eye on everything ;)

**Pull request merged**
