### PR TITLE
made user fields for downloads configurable

### PR DESCRIPTION
**Pull request by t-schroeder**
This only concerns additional user fields, i.e. everything except the
name. First and last name are always exported (not configurable).

### CODE REVIEW

**Comment by t-schroeder** [comment]
Fixes #190

**Comment by justusdieckmann** [comment]
Hey,
thank you very much for you contribution. Sorry it took us so long.
It looks good to me. Could you rebase your branch onto the master? The travis configuration there is working properly.

Greetings,
Justus

**Comment by t-schroeder** [comment]
Hi Justus,

no worries. I rebased on top of master. Hopefully that fixes the travis stuff.

Greetings,
Tim

**Comment by tobiasreischmann** [comment]
Thanks for you contribution :)

**Pull request merged**
