### PR TITLE
Show groups in allocation table, improve allocation table view

### LINKED ISSUE #253: Manual allocation form hard to handle for lots of users and choices
If a trainer wants to edit some or many of the allocations manually, it will become pretty annoying as soon as the count of choices and the count of students increase.

### LINKED ISSUE #254: Allocation table should show groups of students
If choices are restricted by groups the trainer usually also want to see in which groups the students are when he looks at the allocation table, but even more important, when he edits the allocations in the manual allocation form.

### PR DESCRIPTION
**Pull request by PhMemmel**
Closes #253
Closes #254

Additional info: The table will now keep a fixed percentage of the viewport height. This allows the trainer to zoom out in the browser to increase the count of users he is seeing at the same time. This means: The bigger your screen the easier it is for you to edit the allocations manually while it is still ok for users with smaller screens.

### CODE REVIEW

**Review by Laur0r — COMMENTED** [review]
Dear @PhMemmel, thank you for this PR! 

I agree that the usability for the table needs to be improved if there are many users and choices. However, when limiting the height of the table, this introduces a vertical table scrolling within the vertical scrolling of the site. I find this hard to navigate especially when using a tablet or mobile phone. I would rather suggest docking the horizontal column headers as suggested in #212 or to decrease the number of users per page to avoid an additional scrolling.

I also think that with the group restrictions, the groups should be visible in this table. However, through your changes only the associated groups for the users are displayed and not the group restrictions for the choices, which would be crucial to know when editing the allocations. I would suggest adding a group filter which is applied to all choices and users, displaying only those users with the filtered group and the choices allowing this group to be allocated. This could also increase clarity when there are many users and choices with different groups.

**Comment by PhMemmel** [comment]
Hi @Laur0r, thank you very much for your feedback.

Scrolling issue: While I would say that it's someone's own fault when he/she tries to assign many users to many choices manually on a mobile device :-) also on a desktop device your suggestion is better and I finally made it work. I pushed a commit on top. I also pushed another commit which now also makes the group column sticky (I realized I forgot about it while testing). Unfortunately I had to set the first column to a fixed width in that specific case. I am not super happy with that, but did not have a better idea.

Group names: The main reason this feature has been requested by our users is that the groups of the user should be shown *in the export* of the table: Users want to be able to sort the users by their groups (because the groups often are equal to the school class of the students for example). A filter would not help here, so I suggest to keep the groups column. I also added the groups of the choices to the name of the choices, so it is easier to see and assign.
Aside from that: A group filter would be a very great feature. My suggestion would be to keep it like I did it in this PR. If a group filter is being added, maybe it's fine to hide the groups in the table. However, IMO in case of filtering for multiple different groups it could still be viable to see which groups a user is member of/a choice is restricted to.

**Comment by PhMemmel** [comment]
Hi @justusdieckmann, I very much appreciate your css improvements, especially because my CSS skills are not the best ;-)

It looks really well now and so much better than my suggestion ;-)

I also added another commit on top which extracts the group information of the choices into a separate row directly below the headers in case of when the table is being downloaded, so the groups of the choices will also be visible in the export files.

I decided to go for a separate approach (instead of just adding the groups to the choice name strings) in the export files, because people will probably try to do all kinds of crazy "excel magic" and a separate row would be easier to deal with. What do you think?

**Comment by PhMemmel** [comment]
Sorry for the multiple force pushes, took me a while to figure out, what the issue was. But now all sorted hopefully :-)

**Review by Laur0r — APPROVED** [review]
Thank you both, it looks really good now! :)
I also like the idea of adding a separate row for groups in the downloaded file. If you want to further analyze your data, it is definitely helpful to have a row for that.

**Pull request merged**
