### PR TITLE
Add upper limit per choice

### LINKED ISSUE #227: Feature: "Give points": Possibility to limit points per option
"Give points" is a nice distribution method. It would be even better (and open up to more use cases) if one could set a limit for each of the specified options.

So, for example, as student you have 10 points available to distribute among, let's say, 5 options, but you can at most give 3 points to a single option. With this option the teacher can enforce a real(!) distribution of the points while still allowing the students to weight their preferred options.

As far as I can tell it should be sufficient to restrict the number of points being able to distribute in the student's choice view, so it shouldn't be too big of a deal to implement this feature.

### PR DESCRIPTION
**Pull request by PhMemmel**
Closes #227
Replaces #230 

This replaces #230, it is now properly rebased.

It also includes another commit for defaulting the points per choice to 0. This is especially valuable if you have many choices, because otherwise a user would give points to, for example, 3 choices, but will have to clear out the default "1" value for 15 other ones which is pretty annoying.

### CODE REVIEW

**Comment by Laur0r** [comment]
Thank you for rebasing and updating this pull request! There are still some code checker issues, so I will merge #264 first, which provides the clean up. Then it should be clearer where the errors are :)
However, this may take some weeks with vacation and the upcoming Moodle DACH. Will you be there as well? ;)

**Comment by PhMemmel** [comment]
Will try to be fast at rebasing ;-)

**Comment by PhMemmel** [comment]
Hi @Laur0r, here we go :)

Should be properly rebased and adapted to the Codestyle changes, I also added a commit fixing the unit tests after moving the distribution of unallocated users to an adhoc task. They were considered risky as they generated output due to the adhoc task runs.

**Review by Laur0r — APPROVED** [review]
Hey @PhMemmel,
thanks for the quick rebase and adaptions! Everything looks good to me :)

**Comment by PhMemmel** [comment]
Thank you so much @Laur0r for all the effort put into reviewing and integrating our features and fixes. We are very happy that we have been able to contribute everything we have developed so far and we do not need to maintain our own fork anymore. Future fixes and features will be provided directly to you :-)

Again thank you very much!

**Pull request merged**
